# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06f474a29cc6cef9f6f6091a904f6c87bd8412c9bedc0654a572ed48b24eeb4adac7f764492ba4a109bfd679472c036b23942e03635fe0f43397488d5c809be0

test:
  secret_key_base: c16fabf06aa61f1f51f6dcbf9e9cb6a905ff320a22a5c0222d7ba6aa8fd49a523eee3b0249a8f5994bc6c4ad6c182a96f14673f3414cd6d8faf219d9e443a12a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
